version: 2.1
jobs:
  create_and_deploy_front_end:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:  aws cloudformation deploy  --template-file bucket.yml  --stack-name "${CIRCLE_WORKFLOW_ID:0:7}" --parameter-overrides PipelineID="${CIRCLE_WORKFLOW_ID:0:7}"
      - run: aws s3 sync . s3://"${CIRCLE_WORKFLOW_ID}" --delete
  get_last_deployment_id:   
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:  aws cloudformation \
              list-exports --query "Exports[?Name==\`PipelineID\`].Value" \
              --no-paginate --output text 

  promote_to_production:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:  aws cloudformation deploy \
              --template-file cloudfront.yml \
              --stack-name production-distro \
              --parameter-overrides PipelineID="${CIRCLE_WORKFLOW_ID}"

  clean_up_old_front_end:    
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:  aws s3 rm "s3://${OldPipelineID}" --recursive
      - run:  aws cloudformation delete-stack --stack-name "${PreviousPipelineID}"      
      
workflows:
  my_workflow:
     jobs:
     - create_and_deploy_front_end
     - promote_to_production:
        requires:
          - create_and_deploy_front_end